{{- if .Values.perfanaMcp.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: perfana-mcp
  labels:
    app: perfana-mcp
    chart: {{ include "perfana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.perfanaMcp.service.type }}
  ports:
    - port: {{ .Values.perfanaMcp.service.port }}
      targetPort: {{ .Values.perfanaMcp.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: perfana-mcp
    release: {{ .Release.Name }}
{{- end }} 