{{- if .Values.perfanaChat.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.perfanaChat.service.annotations }}
  annotations:
{{ toYaml .Values.perfanaChat.service.annotations | indent 4 }}
{{- end }}
  name: perfana-chat
  labels:
    app: perfana-chat
    chart: {{ include "perfana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.perfanaChat.service.type }}
  ports:
    - port: {{ .Values.perfanaChat.service.port }}
      targetPort:  {{ .Values.perfanaChat.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: perfana-chat
    release: {{ .Release.Name }}
{{- end }} 