{{- if .Values.perfanaDsWorker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfana-ds-worker
  labels:
    app: perfana-ds-worker
    chart: {{ include "perfana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.perfanaDsWorker.replicaCount }}
  selector:
    matchLabels:
      app: perfana-ds-worker
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.perfanaDsWorker.deploymentStrategy }}
  {{- if ne .Values.perfanaDsWorker.deploymentStrategy "RollingUpdate" }}
    rollingUpdate: null
  {{- end }}
  template:
    metadata:
      labels:
        app: perfana-ds-worker
        release: {{ .Release.Name }}
        {{- with .Values.perfanaDsWorker.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.perfanaDsWorker.annotations }}
      annotations: {{ toYaml .Values.perfanaDsWorker.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.perfanaDsWorker.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.perfanaDsWorker.serviceAccount.name }}
      {{- end}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: perfana-ds-worker
          image: "{{ .Values.perfanaDsWorker.image.repository }}:{{ .Values.perfanaDsWorker.image.tag }}"
          imagePullPolicy: {{ .Values.perfanaDsWorker.image.pullPolicy }}
          {{- with .Values.perfanaDsWorker.command }}
          command:
          {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.perfanaDsWorker.args }}
          args:
          {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: {{ .Values.perfanaDsWorker.service.targetPort }}
              containerPort: {{ .Values.perfanaDsWorker.service.port }}
              protocol: TCP
          env:
          {{- range $key, $value := .Values.perfanaDsWorker.extraEnvSecrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.name }}
                  key: {{ $value.key }}
          {{- end }}
        {{- range $key, $value := .Values.perfanaDsWorker.env }}
            - name: {{ $key }}
              value: '{{ $value }}'
        {{- end }}
          resources:
{{ toYaml .Values.perfanaDsWorker.resources | indent 12 }}
          volumeMounts:
          {{- if .Values.perfanaDsWorker.volumeMounts }}
             {{- toYaml .Values.perfanaDsWorker.volumeMounts | nindent 10 }}
          {{- end }}
      volumes:
      {{- if .Values.perfanaDsWorker.volumes }}
         {{- toYaml .Values.perfanaDsWorker.volumes | nindent 6 }}
      {{- end }}
    {{- with .Values.perfanaDsWorker.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaDsWorker.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaDsWorker.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaDsWorker.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
