{{- if .Values.perfanaChat.enabled -}}
{{- if .Values.perfanaChat.ingress.enabled -}}
{{- $ingressPath := .Values.perfanaChat.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: perfana-chat
  labels:
    app: perfana-chat
    chart: {{ include "perfana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.perfanaChat.ingress.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  {{- if .Values.perfanaChat.ingress.ingressClassName }}
  ingressClassName: {{ .Values.perfanaChat.ingress.ingressClassName }}
  {{- end }}
{{- if .Values.perfanaChat.ingress.tls }}
  tls:
  {{- range .Values.perfanaChat.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    {{- range .Values.perfanaChat.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: perfana-chat
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
{{- end }} 