{{- if .Values.perfanaScheduler.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfana-scheduler
  labels:
    app: perfana-scheduler
    chart: {{ include "perfana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.perfanaScheduler.replicaCount }}
  selector:
    matchLabels:
      app: perfana-scheduler
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: perfana-scheduler
        release: {{ .Release.Name }}
        {{- with .Values.perfanaScheduler.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.perfanaScheduler.annotations }}
      annotations: {{ toYaml .Values.perfanaScheduler.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.perfanaScheduler.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.perfanaScheduler.serviceAccount.name }}
      {{- end}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: perfana-scheduler
          image: "{{ .Values.perfanaScheduler.image.repository }}:{{ .Values.perfanaScheduler.image.tag }}"
          imagePullPolicy: {{ .Values.perfanaScheduler.image.pullPolicy }}
          {{- with .Values.perfanaScheduler.command }}
          command:
          {{ toYaml . | nindent 10 }}
          {{- end}}
          {{- with .Values.containerSecurityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env: # ENV variables for your project
          {{- if .Values.mongoUrl.secretName }}
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: MONGO_URL
                  name: {{ .Values.mongoUrl.secretName }}
          {{- end }}
          {{- range $key, $value := .Values.perfanaScheduler.env }}
            - name: {{ $key }}
              value: '{{ $value }}'
          {{- end }}
          resources:
{{ toYaml .Values.perfanaScheduler.resources | indent 12 }}
          volumeMounts:
          {{- if .Values.perfanaScheduler.volumeMounts }}
             {{- toYaml .Values.perfanaScheduler.volumeMounts | nindent 10 }}
          {{- end }}
          {{- if .Values.existingSecret }}
          - name: perfana-scheduler-secrets
            mountPath: /secrets/mongodb.properties
            subPath: perfana-scheduler-mongodb.properties
          {{- end }}
      volumes:
      {{- if .Values.perfanaScheduler.volumes }}
         {{- toYaml .Values.perfanaScheduler.volumes | nindent 6 }}
      {{- end }}
      {{- if .Values.existingSecret }}
      - name: perfana-scheduler-secrets
        projected:
          sources:
          - secret:
              name: {{ .Values.existingSecret }}
      {{- end }}
    {{- with .Values.perfanaScheduler.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaScheduler.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaScheduler.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
