{{- if .Values.perfanaChat.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfana-chat
  labels:
    app: perfana-chat
    chart: {{ include "perfana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.perfanaChat.replicaCount }}
  selector:
    matchLabels:
      app: perfana-chat
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.perfanaChat.deploymentStrategy }}
  {{- if ne .Values.perfanaChat.deploymentStrategy "RollingUpdate" }}
    rollingUpdate: null
  {{- end }}
  template:
    metadata:
      labels:
        app: perfana-chat
        release: {{ .Release.Name }}
        {{- with .Values.perfanaChat.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.perfanaChat.annotations }}
      annotations: {{ toYaml .Values.perfanaChat.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.perfanaChat.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.perfanaChat.serviceAccount.name }}
      {{- end}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: perfana-chat
          image: "{{ .Values.perfanaChat.image.repository }}:{{ .Values.perfanaChat.image.tag }}"
          imagePullPolicy: {{ .Values.perfanaChat.image.pullPolicy }}
          {{- with .Values.perfanaChat.command }}
          command:
          {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.perfanaChat.args }}
          args:
          {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: {{ .Values.perfanaChat.service.targetPort }}
              containerPort: {{ .Values.perfanaChat.service.port }}
              protocol: TCP
          livenessProbe:
           failureThreshold: 8
           httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
           initialDelaySeconds: 30
           periodSeconds: 10
           successThreshold: 1
           timeoutSeconds: 5
          readinessProbe:
           failureThreshold: 3
           httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
           initialDelaySeconds: 10
           periodSeconds: 10
           successThreshold: 1
           timeoutSeconds: 5
          env:
          {{- range $key, $value := .Values.perfanaChat.extraEnvSecrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.name }}
                  key: {{ $value.key }}
          {{- end }}
        {{- range $key, $value := .Values.perfanaChat.env }}
            - name: {{ $key }}
              value: '{{ $value }}'
        {{- end }}
          resources:
{{ toYaml .Values.perfanaChat.resources | indent 12 }}
          volumeMounts:
          {{- if .Values.perfanaChat.volumeMounts }}
             {{- toYaml .Values.perfanaChat.volumeMounts | nindent 10 }}
          {{- end }}
      
      volumes:
      {{- if .Values.perfanaChat.volumes }}
         {{- toYaml .Values.perfanaChat.volumes | nindent 6 }}
      {{- end }}
      
    {{- with .Values.perfanaChat.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaChat.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaChat.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaChat.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }} 