{{- if and .Values.basicAuth.enabled .Values.basicAuthSecret.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  {{- if .Values.basicAuthSecret.name }}
  name: {{ .Values.basicAuthSecret.name }}
  {{- else }}
  name: {{ template "perfana-secure-gateway.fullname" . }}-basic-auth
  {{- end }}
data:
  htpasswd: {{ b64enc (htpasswd .Values.basicAuthSecret.username .Values.basicAuthSecret.password) }}
{{- end }}
