apiVersion: v1
kind: Service
metadata:
  name: {{ include "perfana-secure-gateway.fullname" . }}
  labels:
    {{- include "perfana-secure-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ if .Values.service.grpcPort }}{{ .Values.service.grpcPort }}{{ else }}4317{{ end }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "perfana-secure-gateway.selectorLabels" . | nindent 4 }}
