{{- if .Values.tlsAuthSecret.create }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  {{- if .Values.tlsAuthSecret.name }}
  name: {{ .Values.tlsAuthSecret.name }}
  {{- else }}
  name: {{ template "perfana-secure-gateway.fullname" . }}-tls-auth
  {{- end }}
data:
  tls.crt: {{ .Values.tlsAuthSecret.secretData.certificate | b64enc }}
  tls.key: {{ .Values.tlsAuthSecret.secretData.privateKey | b64enc }}
{{- end }}
